version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msv_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: msv_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msv-usuarios:
    container_name: msv-usuarios
    image: josuechumacero/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msv-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./msv-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  msv-cursos:
    container_name: msv-cursos
    image: josuechumacero/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./msv-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file: ./msv-cursos/.env
    networks:
      - spring
    restart: always
    depends_on:
      - postgres14
      - msv-usuarios
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
networks:
  spring:
    name: spring

